version: "3.5"

services:
  entry:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80

    volumes:
      - ./static:/usr/share/nginx/html/static:rw 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw

    networks:
      challenge:
        aliases:
          - entry.challenge

  frontend:
    image: frontend
    restart: always

    expose:
      - 80

    networks:
      challenge:
        aliases:
          - frontend.challenge

  backend:
    image: backend
    restart: always

    volumes:
      - ./static:/app/static/:rw

    env_file:
      - ./.env

    expose:
      - 8000

    networks:
      challenge:
        aliases:
          - backend.challenge

  db:
    image: mysql:9.0.1
    restart: always

    env_file:
      - ./.env

    expose:
      - 3306

    volumes:
      - ./db:/var/lib/mysql:rw

    networks:
      challenge:
        aliases:
          - db.challenge    

networks:
  challenge:
    name: challenge_new
